# Generated by Django 4.1.2 on 2022-11-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=2, upload_to='images'),
            preserve_default=False,
        ),
    ]
